version: "3.8"
services:
  server:
    image: ghcr.io/protoseo/ngrinder-example:main
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ngrinder_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci",  "--lower_case_table_names=1"]
