version: "3.8"
services:
  controller:
    image: ngrinder/controller:3.5.8
    container_name: ngrinder-controller
    ports:
      - "80:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder/controller:/opt/ngrinder-controller
  agent-1:
    image: ngrinder/agent:3.5.8
    container_name: ngrinder-agent-1
    volumes:
      - ./ngrinder/agent-1:/opt/ngrinder-agent
    command: [ "ngrinder-controller:80" ]
  agent-2:
    image: ngrinder/agent:3.5.8
    container_name: ngrinder-agent-2
    volumes:
      - ./ngrinder/agent-2:/opt/ngrinder-agent
    command: [ "ngrinder-controller:80" ]
