spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ngrinder_test
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      schema-locations: classpath*:schema.sql
      data-locations: classpath*:data.sql
      mode: always
